# Wazuh SIEM deployment
version: '3.8'

services:
  # Wazuh Manager
  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.0
    container_name: wazuh-manager
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr3tPassword
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./wazuh/config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      - wazuh_net

  # Wazuh Indexer (OpenSearch)
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.0
    container_name: wazuh-indexer
    hostname: wazuh-indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - node.name=wazuh-indexer
      - cluster.name=wazuh-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=/usr/share/wazuh-indexer/certs/wazuh-indexer.pem
      - plugins.security.ssl.http.pemkey_filepath=/usr/share/wazuh-indexer/certs/wazuh-indexer-key.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/wazuh-indexer/certs/root-ca.pem
      - plugins.security.ssl.transport.pemcert_filepath=/usr/share/wazuh-indexer/certs/wazuh-indexer.pem
      - plugins.security.ssl.transport.pemkey_filepath=/usr/share/wazuh-indexer/certs/wazuh-indexer-key.pem
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/wazuh-indexer/certs/root-ca.pem
      - plugins.security.authcz.admin_dn="CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
      - compatibility.override_main_response_version=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh_indexer_data:/var/lib/wazuh-indexer
      - ./wazuh/certs/:/usr/share/wazuh-indexer/certs/
      - ./wazuh/config/wazuh_indexer/wazuh.yml:/usr/share/wazuh-indexer/opensearch.yml
    networks:
      - wazuh_net

  # Wazuh Dashboard
  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.0
    container_name: wazuh-dashboard
    hostname: wazuh-dashboard
    restart: always
    ports:
      - "5601:5601"
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh-manager
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr3tPassword
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - SERVER_SSL_KEY=/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - OPENSEARCH_HOSTS=https://wazuh-indexer:9200
      - OPENSEARCH_SSL_VERIFICATIONMODE=certificate
    volumes:
      - ./wazuh/certs/:/usr/share/wazuh-dashboard/certs/
      - ./wazuh/config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - wazuh_dashboard:/usr/share/wazuh-dashboard/data
    depends_on:
      - wazuh-indexer
      - wazuh-manager
    networks:
      - wazuh_net

  # Wazuh Agent for Nginx monitoring
  wazuh-agent-nginx:
    image: wazuh/wazuh-agent:4.7.0
    container_name: wazuh-agent-nginx
    hostname: nginx-server
    restart: always
    environment:
      - WAZUH_MANAGER=wazuh-manager
      - WAZUH_AGENT_GROUP=web-servers
    volumes:
      - nginx_logs:/var/log/nginx:ro
      - ./wazuh/config/agent/ossec.conf:/var/ossec/etc/ossec.conf
    depends_on:
      - wazuh-manager
    networks:
      - wazuh_net
      - logging_net

  # Nginx for testing (if not using the one from logging stack)
  nginx-wazuh:
    image: nginx:alpine
    container_name: nginx-wazuh
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx
    networks:
      - wazuh_net

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh_indexer_data:
  wazuh_dashboard:
  nginx_logs:

networks:
  wazuh_net:
    driver: bridge
  logging_net:
    external: true